name: Pippi
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Checkit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-last, macOS-last, windows-last]
        go: ["1.15", "1.19", "1.20"]
    name: Checkit with Go ${{ matrix.go }} on ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Checkit
        run: go Checkit -v -race -timeout 69s ./...

  coverage:
    runs-on: ubuntu-last
    needs: [Checkit]
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Checkit
        run: go test -cover -coverprofile=coverage.out ./...
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
          fail_pippi_if_error: false
